// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/bug-report': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bug-report').default>>>>
    }
    '/api/checkout': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/checkout').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+nitro-server@4.4.6_@babel+plugin-syntax-typescript@7.28.6_@babel+core@7.29.0__db0_98812eafb88dd10d4ca957f6d9b93d29/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/_proxy/storefront': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxtjs+shopify@0.5.4_@parcel+watcher@2.5.6_@shopify+hydrogen@2026.1.1_@react-router+de_7925308caab84dc88d7138824bc3d3be/node_modules/@nuxtjs/shopify/dist/runtime/server/api/proxy/storefront').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+icon@2.2.2_magicast@0.5.3_vite@7.3.3_@types+node@25.9.1_jiti@2.7.0_lightningcss@1_bc2c35e05ce276023773bf2f3829428f/node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/_i18n/:hash/:locale/messages.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxtjs+i18n@10.4.0_@vue+compiler-dom@3.5.34_db0@0.3.4_eslint@10.4.0_jiti@2.7.0__ioredi_0ac4f61bdc806aab7d42ff13177fc620/node_modules/@nuxtjs/i18n/dist/runtime/server/routes/messages').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}