// Generated by auto imports
export {}
declare global {
  const useRuntimeConfig: (event?: import('h3').H3Event) => import('nuxt/schema').RuntimeConfig
  const useAppConfig: () => import('nuxt/schema').AppConfig
  const defineAppConfig: <C extends import('nuxt/schema').AppConfigInput>(config: C) => C
  const createError: typeof import('h3')['createError']
  const setResponseStatus: typeof import('h3')['setResponseStatus']
  const ARTICLE_FRAGMENT: typeof import('../../graphql/fragments/blog').ARTICLE_FRAGMENT
  const BLOG_FRAGMENT: typeof import('../../graphql/fragments/blog').BLOG_FRAGMENT
  const CART_FRAGMENT: typeof import('../../graphql/fragments/cart').CART_FRAGMENT
  const CART_LINE_CONNECTION_FRAGMENT: typeof import('../../graphql/fragments/cart').CART_LINE_CONNECTION_FRAGMENT
  const CART_LINE_FRAGMENT: typeof import('../../graphql/fragments/cart').CART_LINE_FRAGMENT
  const CART_USER_ERRORS_FRAGMENT: typeof import('../../graphql/fragments/cart').CART_USER_ERRORS_FRAGMENT
  const COLLECTION_CONNECTION_FRAGMENT: typeof import('../../graphql/fragments/collection').COLLECTION_CONNECTION_FRAGMENT
  const COLLECTION_FRAGMENT: typeof import('../../graphql/fragments/collection').COLLECTION_FRAGMENT
  const CUSTOMER_FRAGMENT: typeof import('../../graphql/fragments/customer').CUSTOMER_FRAGMENT
  const IMAGE_FRAGMENT: typeof import('../../graphql/fragments/utils').IMAGE_FRAGMENT
  const MENU_FRAGMENT: typeof import('../../graphql/fragments/menu').MENU_FRAGMENT
  const MENU_ITEM_FRAGMENT: typeof import('../../graphql/fragments/menu').MENU_ITEM_FRAGMENT
  const PRICE_FRAGMENT: typeof import('../../graphql/fragments/utils').PRICE_FRAGMENT
  const PRODUCT_CONNECTION_FRAGMENT: typeof import('../../graphql/fragments/product').PRODUCT_CONNECTION_FRAGMENT
  const PRODUCT_FILTERS_FRAGMENT: typeof import('../../graphql/fragments/product').PRODUCT_FILTERS_FRAGMENT
  const PRODUCT_FRAGMENT: typeof import('../../graphql/fragments/product').PRODUCT_FRAGMENT
  const PRODUCT_OPTION_FRAGMENT: typeof import('../../graphql/fragments/product').PRODUCT_OPTION_FRAGMENT
  const PRODUCT_VARIANT_CONNECTION_FRAGMENT: typeof import('../../graphql/fragments/product').PRODUCT_VARIANT_CONNECTION_FRAGMENT
  const PRODUCT_VARIANT_FRAGMENT: typeof import('../../graphql/fragments/product').PRODUCT_VARIANT_FRAGMENT
  const cartGetInputSchema: typeof import('../../graphql/validation/cart').cartGetInputSchema
  const cartLineInputSchema: typeof import('../../graphql/validation/cart').cartLineInputSchema
  const cartRemoveInputSchema: typeof import('../../graphql/validation/cart').cartRemoveInputSchema
  const cartUpdateInputSchema: typeof import('../../graphql/validation/cart').cartUpdateInputSchema
  const categoryFilterSchema: typeof import('../../graphql/validation/utils').categoryFilterSchema
  const collectionInputSchema: typeof import('../../graphql/validation/collection').collectionInputSchema
  const connectionParamsSchema: typeof import('../../graphql/validation/utils').connectionParamsSchema
  const flattenConnection: typeof import('../../node_modules/.pnpm/@nuxtjs+shopify@0.5.4_@parcel+watcher@2.5.6_@shopify+hydrogen@2026.1.1_@react-router+de_7925308caab84dc88d7138824bc3d3be/node_modules/@nuxtjs/shopify/dist/runtime/utils/flattenConnection').flattenConnection
  const localizationParamsSchema: typeof import('../../graphql/validation/utils').localizationParamsSchema
  const menuGetInputSchema: typeof import('../../graphql/validation/menu').menuGetInputSchema
  const metafieldFilterSchema: typeof import('../../graphql/validation/utils').metafieldFilterSchema
  const predictiveSearchParamsSchema: typeof import('../../graphql/validation/utils').predictiveSearchParamsSchema
  const priceRangeFilterSchema: typeof import('../../graphql/validation/utils').priceRangeFilterSchema
  const productConnectionParamsSchema: typeof import('../../graphql/validation/product').productConnectionParamsSchema
  const productFilterSchema: typeof import('../../graphql/validation/product').productFilterSchema
  const productInputSchema: typeof import('../../graphql/validation/product').productInputSchema
  const productSortKeysSchema: typeof import('../../graphql/validation/product').productSortKeysSchema
  const taxonomyMetafieldFilterSchema: typeof import('../../graphql/validation/utils').taxonomyMetafieldFilterSchema
  const variantOptionFilterSchema: typeof import('../../graphql/validation/utils').variantOptionFilterSchema
}